name: dbt CI

on:
  pull_request:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      KEYFILE_LOCATION:       /tmp/google/google-service-account.json
      BIGQUERY_KEYFILE:       ${{ secrets.BIGQUERY_KEYFILE }}
      BIGQUERY_PROJECT:       ${{ secrets.BIGQUERY_PROJECT }}
      BIGQUERY_DATASET_PROD:  ${{ secrets.BIGQUERY_DATASET_PROD }}
      DBT_PROFILES_DIR:       .          # repo root holds profiles.yml

    steps:
            # Prep Google keyfile
      - run: mkdir -p "$(dirname $KEYFILE_LOCATION)" 
      - run: echo "$BIGQUERY_KEYFILE" > $KEYFILE_LOCATION

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Verify connection to BigQuery prod
        run: dbt debug --target prod